# Generated by Django 5.2.5 on 2025-08-31 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.UUIDField(auto_created=True, db_index=True, primary_key=True, serialize=False)),
                ('player_name', models.CharField(default='anonymous', max_length=20, unique=True, verbose_name='Имя игрока')),
                ('last_entry', models.DateField(auto_now_add=True, null=True, verbose_name='последний вход')),
                ('last_boost_date', models.DateField(default=None, null=True, verbose_name='последний буст')),
                ('player_score', models.BigIntegerField(default=0)),
                ('rewarded', models.JSONField(default=dict, verbose_name='Награды')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['player_id'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=30, verbose_name='Усиление')),
                ('description', models.CharField(default='None', max_length=30, null=True, verbose_name='Усиление')),
                ('active', models.BooleanField(default=True)),
                ('get_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(default=None, null=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='players.player', verbose_name='усилитель')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.level')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='LevelPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.DateField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.level')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.prize')),
            ],
        ),
    ]
